# Explain function,syntax,code and application of the following:

# 1.Eigen values and eigen vectors of an array

In [2]:
#Syntax:-
#numpy.linalg.eig()
import numpy as np
a=np.array([[1,2],[3,4]])
w,v=np.linalg.eig(a)
print(w)#It gives eigen values
print(v)#gives eigen vectors corresponding to eigen values

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# 2.digitize()

In [4]:
# Syntax:-
#np.digitize(Array, Bin, Right)
#Code
import numpy as np 
a = np.array([1.7, 2.5, 3.7, 4.9]) 
bins = np.array([1.0, 1.3, 2.5, 4.0, 10.0]) 
  
# using np.digitize() method 
dig = np.digitize(a, bins) 
  
print(dig) 

[2 3 3 4]


# 3.repeat()

In [5]:
#Syntax:-
#np.repeat(element to be repeated,number of times it is to be repeated)
#Code:-
import numpy as np
np.repeat(3,7)

array([3, 3, 3, 3, 3, 3, 3])

# 4.squeeze()

In [6]:
# Syntax:-
#numpy.squeeze(arr, axis=None )
#Code:-
import numpy as np
a= np.array([[[3, 3, 3], [3, 3, 3]]]) 
print ("Input array : ", a)  
print("Shape of input array : ", a.shape)   
b = np.squeeze(a)  
print ("squeezed array : ", b) 
print("Shape of output array : ", b.shape)

Input array :  [[[3 3 3]
  [3 3 3]]]
Shape of input array :  (1, 2, 3)
squeezed array :  [[3 3 3]
 [3 3 3]]
Shape of output array :  (2, 3)


# 5.linspace()

In [8]:
#Syntax:-
#numpy.linspace(start,stop,num = 50,endpoint = True,retstep = False,dtype = None)
#code:-
import numpy as np
  
# restep set to True 
print("B", np.linspace(2.0, 3.0, num=5, retstep=True)) 
  
# To evaluate sin() in long range  
x = np.linspace(0, 2, 10) 
print("A", np.sin(x)) 

B (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


# 6.Clip()

In [9]:
#Syntax:-
#numpy.clip(a, a_min, a_max, out=None)
#code:-
import numpy as np 
c = [1, 2, 3, 4, 5, 6, 7, 8 ] 
print ("Input array : ", c) 
b= np.clip(c, a_min = 2, a_max = 6) 
print ("Output array : ",b) 

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [2 2 3 4 5 6 6 6]


# 7.Extract()

In [10]:
#Syntax:-
#numpy.extract(condition, array)
#Code:-
import numpy as np 
  
x = np.arange(10).reshape(5, 2) 
print("Original array : ", x) 
  
a = np.mod(x, 4) !=0
# This will show element status of satisfying condition 
print("Array Condition a : ", a) 
  
# This will return elements that satisy condition "a" condition 
print("Elements that satisfy condition a  : ", np.extract(a,x))  
b = x - 4 == 1
# This will show element status of satisfying condition 
print("Array Condition b : ", b) 
  
# This will return elements that satisy condition "b" condition 
print("Elements that satisfy condition b  : ", np.extract(b,x)) 

Original array :  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Array Condition a :  [[False  True]
 [ True  True]
 [False  True]
 [ True  True]
 [False  True]]
Elements that satisfy condition a  :  [1 2 3 5 6 7 9]
Array Condition b :  [[False False]
 [False False]
 [False  True]
 [False False]
 [False False]]
Elements that satisfy condition b  :  [5]


# 8.argpartition()

In [12]:
# Syntax:-
#numpy.argpartition(arr, kth, axis=-1, kind=’introselect’, order=None)
#Code:-
import numpy as np 
a = np.array([[ 2, 0,  1], [ 5, 4, 9] ]) 
print ("Input array : \n", a)  
  
b= np.argpartition(a, 1, axis = 1) 
print ("Output partitioned array indices :\n ", b) 

Input array : 
 [[2 0 1]
 [5 4 9]]
Output partitioned array indices :
  [[1 2 0]
 [1 0 2]]


# 9.setdiff1d()

In [1]:
# Syntax:-
#numpy.setdiff1d(arr1, arr2, assume_unique = False)
#Code:-
import numpy as np 
a= [5, 6, 2, 3, 4] 
b= [1, 2, 3] 
   
dif= np.setdiff1d(a,b) 
   
print (dif) 

[4 5 6]


# 10.itemsize

In [3]:
# Syntax:-
#numpy.ndarray.itemsize(arr)
#Code:-
import numpy as np 
  
a= np.array([1, 2, 3, 4], dtype = np.float64) 
  
s = a.itemsize 
  
print (s) 

8


# 11.hstack()

In [4]:
#Syntax:-
#numpy.hstack(tup)
#Code:-
import numpy as np 
  
# input array 
a = np.array([ 1, 2, 3] ) 
print ("1st Input array : ", a)  
  
b = np.array([ 4, 5, 6] ) 
print ("2nd Input array : ", b)  
  
# Stacking the two arrays horizontally 
o = np.hstack((a, b)) 
print ("Output horizontally stacked array:", o) 

1st Input array :  [1 2 3]
2nd Input array :  [4 5 6]
Output horizontally stacked array: [1 2 3 4 5 6]


# 12.vstack()

In [5]:
#Syntax:-
#numpy.vstack(tup)
#Code:-
import numpy as np 
# input array
a = np.array([ 1, 2, 3] ) 
print ("1st Input array : ", a)  
  
b= np.array([ 4, 5, 6] ) 
print ("2nd Input array : ", b)  
  
# Stacking the two arrays vertically 
o = np.vstack((a,b)) 
print ("Output vertically stacked array: ", o) 

1st Input array :  [1 2 3]
2nd Input array :  [4 5 6]
Output vertically stacked array:  [[1 2 3]
 [4 5 6]]


# 13.hsplit()

In [6]:
#Syntax:-
# numpy.hsplit(arr, indices_or_sections)
#Code:-
import numpy as np
a = np.arange(16.0).reshape(4, 4) 
b= np.hsplit(a, 2) 
print (b)

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


# 14.vsplit()

In [7]:
#Syntax:-
#numpy.vsplit(arr, indices_or_sections)
#Code:-
import numpy as np
a = np.arange(9.0).reshape(3, 3) 
b= np.vsplit(a, 1) 
print (b) 

[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]


# 15.view vs shallow copy

In [9]:
import numpy as np
import copy

x = np.array([10, 11, 12, 13])

# Create views of x (shallow copies sharing data) in 2 different ways
x_view1 = x.view()
x_view2 = x[:]          # Creates a view using a slice

# Create full copies of x (not sharing data) in 2 different ways
x_copy1 = x.copy()
x_copy2 = copy.copy(x)  # Calls x.__copy__() which creates a full copy of x

# Change some array elements to see what happens
x[0]       = 555        # Affects x, x_view1, and x_view2
x_view1[1] = 666        # Affects x, x_view1, and x_view2
x_view2[2] = 777        # Affects x, x_view1, and x_view2
x_copy1[0] = 888        # Affects only x_copy1
x_copy2[0] = 999        # Affects only x_copy2

print(x)                # [555 666 777  13]
print(x_view1)          # [555 666 777  13]
print(x_view2)          # [555 666 777  13]
print(x_copy1)          # [888  11  12  13]
print(x_copy2)          # [999  11  12  13]

[555 666 777  13]
[555 666 777  13]
[555 666 777  13]
[888  11  12  13]
[999  11  12  13]


# 16.Deep Copy

In [11]:
import copy 
  
# initializing list 1 
a = [1, 2, [3,5], 4] 
  
# using deepcopy to deep copy  
b = copy.deepcopy(a) 
  
# original elements of list 
print ("The original elements before deep copying") 
for i in range(0,len(a)): 
    print (a[i],end=" ") 
  
print("\r") 
  
# adding and element to new list 
b[2][0] = 7
  
# Change is reflected in l2  
print ("The new list of elements after deep copying ") 
for i in range(0,len( a)): 
    print (b[i],end=" ") 
print("\r") 
  
# Change is NOT reflected in original list 
# as it is a deep copy 
print ("The original elements after deep copying") 
for i in range(0,len( a)): 
    print (a[i],end=" ") 

The original elements before deep copying
1 2 [3, 5] 4 
The new list of elements after deep copying 
1 2 [7, 5] 4 
The original elements after deep copying
1 2 [3, 5] 4 

# 17.Copy()

In [13]:
import copy 
  
# initializing list 1  
a = [1, 2, [3,5], 4] 
  
# using copy for shallow copy   
b = copy.copy(a)  
  
# using deepcopy for deepcopy   
c= copy.deepcopy(a)
print(b)
print(c)

[1, 2, [3, 5], 4]
[1, 2, [3, 5], 4]


# 18.meshgrid()

In [14]:
import numpy as np 
import matplotlib.pyplot as plt # pyplot imported for plotting graphs 
x = np.linspace(-4, 4, 9)   
y = np.linspace(-5, 5, 11) 
  
# The meshgrid function returns 
# two 2-dimensional arrays  
x1, y1 = np.meshgrid(x, y) 
  
print("x1 = ") 
print(x1) 
print("y1 = ") 
print(y1) 

x1 = 
[[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]]
y1 = 
[[-5. -5. -5. -5. -5. -5. -5. -5. -5.]
 [-4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.]]


# 19.swapaxes()

In [15]:
#Syntax:-
# numpy.swapaxes(arr, axis1, axis2)
#Code:-
import numpy as np
a = np.array([[2, 4, 6]]) 
b = np.swapaxes(a, 0, 1) 
print (b) 

[[2]
 [4]
 [6]]


# 20.column_stack()s

In [16]:
#Syntax:-
#numpy.column_stack(tup)
#Code:-
import numpy as np
# input array 
a = np.array(( 1, 2, 3 )) 
print ("1st Input array : \n", a)  
  
b = np.array(( 4, 5, 6 )) 
print ("2nd Input array : \n", b)  
  
# Stacking the two arrays  
op = np.column_stack((a, b)) 
print ("Output stacked array:\n ", op) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output stacked array:
  [[1 4]
 [2 5]
 [3 6]]
